name: Build & test
run-name: Testing Aegis
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Get the only thing that usually is reliable in CI
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - name: Update dependencies
        run: nix-shell -p elan --run "lake update"
      - name: Download mathlib4 cache
        run: nix-shell -p elan --run "lake exe cache get"
      - name: Build the framework
        run: nix-shell -p elan --run "lake build"
      - name: Verify the expected output of our tests
        run: nix-shell -p elan --run "diff -u Aegis/Tests/Test.expected.out <(lake env lean Aegis/Tests/Test.lean)"
