name: Build
run-name: Building sierra-lean
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Get the only thing that usually is reliable in CI
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-23.05
      - name: Download mathlib4 cache
        run: nix-shell -p elan --run "lake exe cache get"
      - name: Build the framework
        run: nix-shell -p elan --run "lake build"
